server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

swagger:
  enable: true
spring:
  mvc:
    view:
      prefix: /templates
      suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
  rabbitmq:
    addresses: 101.201.100.206
    port: 5672
    username: admin
    password: admin

